blog/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required


from . import views

from django.contrib.sitemaps.views import sitemap
from sitemap import BlogSitemap, ViewSitemap

# a dictionary of sitemaps
sitemaps = {
	'views': ViewSitemap,
    'blog': BlogSitemap
}

app_name = 'blog'
urlpatterns = [
	# url(r'^$entry/', views.PostListView.as_view(), name='entry'),
	url(r'^$', views.index, name='index'),
    url(r'^events/$', views.events, name='events'),
    url(r'^jobs/$', views.JobListView.as_view(), name='jobs'),   
    url(r'^share/$', views.post, name='post'),
    url(r'^publish-event/$', login_required(views.event), name='event'),
    # url(r'^publicar-evento/$', login_required(views.event), name='event'),
    url(r'^submit-job/$', login_required(views.job), name='job'),
    url(r'^panel/', login_required(views.panel), name='panel'), 
    url(r'^users/', login_required(views.users), name='users'), 
    # url(r'^dashboard/', views.dashboard, name='dashboard'), 
    url(r'^about/', views.AboutView.as_view(), name='about'), 
    url(r'^success-payment/', views.SuccessPaymentView.as_view(), name='success-payment'), 
    url(r'^faq/', views.FaqView.as_view(), name='faq'), 
    url(r'^terms/', views.TermsView.as_view(), name='terms'), 
    url(r'^privacy/', views.PrivacyView.as_view(), name='privacy'), 
    url(r'^bye/', views.UnsubscribedView.as_view(), name='unsubscribed'), 
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^newsletter/', views.NewsletterView.as_view(), name='newsletter'), 
    url(r"^checkout$", views.checkout, name="checkout_page")
]

earlist/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^accounts/profile/votes/(?P<slug>[^\.]+)/vote/(?P<direction>[^\.]+)/$', views.vote, name='vote'),
    url(r'^accounts/profile/posts/(?P<slug>[^\.]+)/vote/(?P<direction>[^\.]+)/$', views.vote, name='vote'),
    url(r'^panel/status/(?P<slug>[^\.]+)/(?P<message>[0-9]+)/$', login_required(views.status), name='status'),
    url(r'^admin/', admin.site.urls),
    # url('^', include('django.contrib.auth.urls')),
	url(r'^', include('blog.urls')),
    url(r'^accounts/profile/(?P<view>[^\.]+)/$', login_required(views.profile), name='profile'),
    url(r'^company/(?P<slug>[^\.]+)/$', views.DetailView.as_view(), name='detail'), 
    url(r'^accounts/', include('allauth.urls')),
    url(r'^success-post/(?P<slug>[^\.]+)/$', login_required(views.SuccessPostView.as_view()), name='success-post'), 
    url(r'^success-event/(?P<pk>\d+)/$', login_required(views.SuccessEventView.as_view()), name='success-event'), 
    url(r'^publish/', views.ContributeView.as_view(), name='contribute'), 
    url(r'^update-post/(?P<slug>[^\.]+)/$', login_required(views.PostUpdateView.as_view()), name='update-post'), 
    url(r'^delete-post/(?P<slug>[^\.]+)/$', login_required(views.PostDeleteView.as_view()), name='delete-post'),
    url(r'^(?P<slug>[^\.]+)/vote/(?P<direction>[^\.]+)$', views.vote, name='vote'),
    # url(r'^newsletter', views.newsletter, name='newsletter'),
    url(r'^unsubscribe/g7704n83y6RS93o206QJ87R9UZV46Vn0/(?P<id>[0-9]+)/33325y0aTp/$', views.unsubscribe, name='newsletter'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import permalink
from django.core.urlresolvers import reverse
from meta.models import ModelMeta
import datetime

class Post(ModelMeta, models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(max_length=200, unique=True)
	slogan = models.CharField(max_length=200)
	body = models.TextField()
	link = models.URLField(max_length=200, unique=True)
	image_file = models.FileField(upload_to='images/%Y%m%d', blank=True)
	city = models.CharField(max_length=200)
	approved = models.IntegerField(default=0)
	votes = models.IntegerField(default=0)
	sponsored = models.BooleanField(default=False, blank=True)
	charge_id = models.CharField(max_length=500, blank=True)
	date = models.DateField(auto_now_add=True)
	created_at = models.DateTimeField(db_index=True, auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	# image_url = models.URLField(max_length=1000)
	# category = models.ForeignKey('Category')

	def __str__(self):
		return self.title.encode('utf-8')

	def get_absolute_url(self):
		return reverse('detail', kwargs={'slug':self.slug})

class Voter(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(db_index=True, auto_now_add=True)

class Newsletter(models.Model):
    email = models.CharField(max_length=200)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
		return self.email

class Unsubscribed(models.Model):
    email = models.CharField(max_length=200)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
		return self.email


class Event(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=200)
	# slug = models.SlugField(max_length=200)
	body = models.CharField(max_length=200)
	link = models.CharField(max_length=200)
	image_file = models.FileField(upload_to='images/%Y%m%d', blank=True)
	date = models.DateField(null=True)
	time = models.TimeField(null=True)
	approved = models.IntegerField(default=0)
	created_at = models.DateTimeField(db_index=True, auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

class Job(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)
	company = models.CharField(max_length=200)
	link = models.URLField(max_length=200, unique=True)
	image_url = models.URLField(max_length=1000)
	created_at = models.DateTimeField(db_index=True, auto_now_add=True)

	def __str__(self):
		return self.title

class Sponsor(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	link = models.URLField(max_length=200, unique=True)
	image_file = models.FileField(upload_to='images/%Y%m%d', blank=True)
	created_at = models.DateTimeField(db_index=True, auto_now_add=True)

	def __str__(self):
		return self.title



# class Category(models.Model):
# 	title = models.CharField(max_length=200, db_index=True)
# 	slug = models.SlugField(max_length=200, db_index=True)

# 	def __str__(self):
# 		return self.title

blog/forms.py
from django import forms
 
class PostForm(forms.Form):
    title = forms.CharField(max_length=200)
    slogan = forms.CharField(max_length=200)
    body = forms.CharField(widget=forms.Textarea)
    link = forms.URLField(max_length=200)
    # image_url = forms.URLField(max_length=200)
    image_file = forms.FileField(label='Selecciona un archivo')
    city = forms.CharField(max_length=200)

class EventForm(forms.Form):
    title = forms.CharField(max_length=200)
    body = forms.CharField(max_length=200)
    link = forms.URLField(max_length=200)
    image_file = forms.FileField(label='Selecciona un archivo', required=False)
    date_time = forms.DateTimeField()

class JobForm(forms.Form):
    title = forms.CharField(max_length=200)
    company = forms.CharField(max_length=200)
    link = forms.URLField(max_length=200)
    image_url = forms.URLField(max_length=200)

blog/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from django.db import IntegrityError
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from .models import Post, Event, Job, Voter, Sponsor
from .forms import PostForm, JobForm,EventForm
from django.utils.text import slugify
from django.contrib.auth import logout
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context, RequestContext
from earlist.secret import api
from earlist.secret import cfg
from earlist.secret import STRIPE_PUBLIC_KEY
import datetime as dt
from datetime import datetime, timedelta
from meta.views import Meta, MetadataMixin
import twitter
import facebook
import stripe
from django.conf import settings
from django.http.response import HttpResponseForbidden
from django.contrib.auth.decorators import user_passes_test

meta = Meta(
        use_og = True,
        use_twitter = True,
        use_facebook = True,
        use_title_tag = True,
        url = "http://earlist.xyz/",
        title = 'Earlist | Discover And Share Amazing Startups',
        description = 'Earlist is the best place to find amazing new products and startups. Share, discover and get access to great companies every day.',
        image = 'http://earlist.xyz/media/images/20180815/earlist.png',
        )

class NewsletterView(generic.TemplateView):
    template_name = "blog/emails/newsletter.html"

    def get_context_data(self, **kwargs):

        how_many_days = 100
        today = dt.date.today()
        p = Post.objects.order_by('-votes').filter(approved=1).filter(date__gte=datetime.now()-timedelta(days=how_many_days))[:5]
        events = Event.objects.order_by('date').filter(date__year=today.year, date__month=today.month)[:3]
        jobs = Job.objects.order_by('-created_at')[:10]
        sponsors = Sponsor.objects.order_by('-created_at')[:2]
        special = Post.objects.order_by('-created_at').filter(approved=1).filter(date__gte=datetime.now()-timedelta(days=how_many_days)).filter(sponsored=1)[:5]


        context = { 'posts_list': p, 'user_unsubscribe_id': self.request.user.id, 'username': self.request.user.username, 'events': events, 'jobs': jobs, 'sponsors':sponsors, 'special': special }

        return context

def events(
        request,
        template='blog/entry_events.html',
        page_template='blog/entry_events_page.html'):

    orders = [ '-created_at']
    today = dt.date.today()

    context = {
        'events_list': Event.objects.order_by('date').filter(date__year=today.year, date__month=today.month),
        'page_template': page_template,
        'meta': meta,
        'today': today,
        'sponsors': Sponsor.objects.order_by('-created_at')
    }

    if request.is_ajax():
        template = page_template
    return render(request, template, context)

class AboutView(generic.TemplateView):
    template_name = "blog/about.html"

class FaqView(generic.TemplateView):
    template_name = "blog/faq.html"

class SuccessPaymentView(generic.TemplateView):
    template_name = "blog/success-payment.html"

class TermsView(generic.TemplateView):
    template_name = "blog/terms.html"

class PrivacyView(generic.TemplateView):
    template_name = "blog/privacy.html"

class ShareView(generic.TemplateView):
    template_name = "blog/share.html"

class UnsubscribedView(generic.TemplateView):
    template_name = "blog/unsubscribed.html"

def unsubscribe(request, id):
    try:
        g = Group.objects.get(name='unsubscribed') 
    except:
        g = Group.objects.create(name='unsubscribed')

    id_user = User.objects.filter(id=id)
    
    g.user_set.add(id_user)

    return HttpResponseRedirect(reverse('blog:unsubscribed'))

def profile(
        request,
        view,
        template='blog/entry_profile.html',
        page_template='blog/entry_profile_page.html'):

    context = {}

    voted = Voter.objects.filter(user=request.user).count()
    posted = Post.objects.filter(user=request.user).count()

    if view == "votes":
        context_list = Voter.objects.filter(user=request.user).order_by('-created_at').all()
        view = 'votes'
    else:
        context_list = Post.objects.filter(user=request.user).order_by('-created_at').all()
        view = 'posts'

    context = {
        'context_list': context_list,
        'page_template': page_template,
        'view' : view,
        'voted' : voted,
        'posted' : posted,
        'meta': meta,
        'sponsors' : Sponsor.objects.order_by('-created_at')
    }

    if request.user.is_authenticated():
        events = Event.objects.filter(user=request.user).order_by('-created_at')
        votes = Voter.objects.filter(user=request.user)
        v_list = []
        for vote in votes:
            v_list.append(vote.post.slug)
            context['votes_list'] = v_list
            context['events'] = events

    if request.is_ajax():
        template = page_template
    
    return render(request, template, context)

def index(
        request,
        template='blog/index.html',
        page_template='blog/index_page.html'):

    orders = [ '-created_at', 'name' ]

    how_many_days = 7
    today = dt.date.today()
    featured_list = Post.objects.order_by('-votes').filter(approved=1).filter(sponsored=1).filter(date__gte=datetime.now()-timedelta(days=how_many_days))

    context = {
        'posts_list': Post.objects.order_by('-date', '-sponsored', '-votes').filter(approved=1),
        'page_template': page_template,
        'meta': meta,
        'panel_count': Post.objects.filter(approved=0).count(),
        'sponsors': Sponsor.objects.order_by('-created_at'),
        'featured_list': featured_list.order_by('-date', '-sponsored', '-votes').filter(approved=1)
    }

    if request.user.is_authenticated():
        votes = Voter.objects.filter(user=request.user)
        v_list = []
        for vote in votes:
            v_list.append(vote.post.slug)
            context['votes_list'] = v_list

    if request.is_ajax():
        template = page_template
    return render(request, template, context)

@csrf_exempt
def vote(request, slug, direction):

    p = Post.objects.get(slug=slug)

    num_results = Voter.objects.filter(user = request.user, post = p).count()

    if num_results < 1:

        p.votes += 1

        voter = Voter.objects.create(
            user = request.user,
            post = p
            )

    else:
        Voter.objects.filter(user=request.user, post = p).delete()
        p.votes -= 1

    p.save()

    return HttpResponse(p.votes)

@csrf_exempt
def status(request, slug, message):

    p = Post.objects.get(slug=slug)
    email = p.user.email

    if message == '1':
        p.approved = 1
        p.updated_at = datetime.now()
        p.date = datetime.now()
        d = Context({ 'first_name': p.user.first_name, 'title': p.title, 'slug': p.slug })
        plaintext = get_template('blog/emails/approved.txt')
        htmly     = get_template('blog/emails/approved.html')
        subject = 'Your post has been approved'

        api.PostMedia("%s: %s http://earlist.xyz/company/%s via @%s" % (p.title, p.slogan, p.slug, p.user), request.build_absolute_uri(p.image_file.url))

        def main():
        # Fill in the values noted in previous steps here

            api = get_api(cfg)
            msg = "%s: %s http://earlist.xyz/company/%s/" % (p.title, p.slogan, p.slug)
            attachment =  {
                'name': p.title + " | Earlist",
                'link': "http://earlist.xyz/company/" + p.slug,
                'caption': p.slogan,
                'description': p.body,
                'picture': request.build_absolute_uri(p.image_file.url)
            }
            status = api.put_wall_post(msg, attachment)

        def get_api(cfg):
            graph = facebook.GraphAPI(cfg['access_token'])
            # Get page token to post as the page. You can skip 
            # the following if you want to post as yourself. 
            resp = graph.get_object('me/accounts')
            page_access_token = None
            for page in resp['data']:
                if page['id'] == cfg['page_id']:
                    page_access_token = page['access_token']
            graph = facebook.GraphAPI(page_access_token)
            return graph

            # You can also skip the above if you get a page token:
            # http://stackoverflow.com/questions/8231877/facebook-access-token-for-pages
            # and make that long-lived token as in Step 3

        main()
        
    else:
        p.approved = 2

        if message == '2':
            error = 'Hay errores en la publicación. Te invitamos a revisar que la imagen se vea bien, que no haya errores en el texto y que se usen el número de caracteres adecuados en la descripción. Puedes editar la publicación en tu perfil.'

        elif message == '3':
            error = 'Por el momento no podremos publicar esto en nuestro sitio. Si lo deseas puedes ser un patrocinador del sitió y aparecer en la zona de los banners. Para más información por favor mandanos un mail a hola@earlist.xyz.'

        else:
            error = 'Este tipo de publicación no está en linea con el tipo de contenido que mostramos en Earlist. Lamentablemente no podremos publicar esto. Te invitamos a seguir siendo parte de nuestra comunidad y a hacer publicaciones que van de acuerdo a nuestro contenido.'

        d = Context({ 'first_name': p.user.first_name, 'error': error, 'title': p.title })
        plaintext = get_template('blog/emails/declined.txt')
        htmly     = get_template('blog/emails/declined.html')
        subject = 'Tu publicacion ha sido declinada'        

blog/templates/blog/contribute.html
{% extends "blog/base.html" %}
{% block meta %}
<meta name="description" content="Earlist is the best place to share amazing products and startups with a great community of early adopters.">

<meta property="og:title" content="Share Startup | Earlist"/>
<meta property="og:description" content="Earlist is the ultimate to go share what’s next on blockchain,  technology, food and beverage, trends and much more."/>
<meta name="twitter:description" content="Earlist is the ultimate to go share what’s next on blockchain,  technology, food and beverage, trends and much more.">

<meta property="og:image" content="http://earlist.xyz/media/images/20180815/earlist.png"/>
<meta property="og:url" content="http://earlist.xyz/publish/"/>
<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="http://earlist.xyz/publish/">
<meta name="twitter:title" content="Publish Startup | Earlist">
<meta name="twitter:image" content="http://earlist.xyz/media/images/20180815/earlist.png">

<title>Publish Startups | Earlist</title>

{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="container p-t-md">
    <div class="row">
<div class="col-sm-offset-2 col-md-8">
  <div class="panel panel-default">
  	<div class="panel-body text-center m-t">
		<h1>Publish on Earlist</h1>
		<i class="fa fa-share-square-o fa-5x text-primary m-t-md"></i>
		<div class="row m-t-md m-b-md">
			<div class="col-lg-1"></div>
			<div class="col-lg-10 m-b-md">
				<p class="lead">Earlist was created to give entrepreneurs and business builders the ability to share their amazing projects with a great community. Share an amazing startup with the Earlist community, it's free!. Remember we love Blockchain, Food and Beverage, Ecommerce and overall tech companies.</p>
			</div>
			<div class="row text-center m-b-md">
				<div class="col-sm-8 col-sm-offset-2">
					<a class="btn btn-lg btn-success" href="{% url 'blog:post' %}">Publish Startup</a>
				</div>
				<!--<div class="col-sm-4">
					<a class="btn btn-lg btn-danger" href="{% url 'blog:event' %}">Publicar Evento</a>
				</div>-->
			</div>
		</div>
	</div>
  </div>
</div>

{% endblock content %}

blog/templates/blog/entry_profile.html
{% extends "blog/base.html" %}
{% block meta %}
<meta name="description" content="Earlist is he place where you can share an amazing startups with a great community.">

<meta property="og:title" content="Your Profile | Earlist"/>
<meta property="og:description" content="Earlist is the ultimate go-to place if you want to discover what’s next on blockchain,  technology, food and beverage, trends and much more."/>
<meta name="twitter:description" content="Earlist is the ultimate go-to place if you want to discover what’s next on blockchain,  technology, food and beverage, trends and much more.">

<meta property="og:image" content="http://earlist.xyz/media/images/20180815/earlist.png"/>
<meta property="og:url" content="http://earlist.xyz/accounts/profile/votes/"/>
<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="http://earlist.xyz/accounts/profile/votes/">
<meta name="twitter:title" content="Your Profile | Earlist">
<meta name="twitter:image" content="http://earlist.xyz/media/images/20180815/earlist.png">

<title>Your Profile | Earlist</title>
{% endblock %}
{% load staticfiles %}
{% block content %}
{{ block.super }}
<div class="container p-t-md">
    <div class="row">
<div class="col-md-3">
  <div class="panel panel-default panel-profile m-b-md">
    {% for account in user.socialaccount_set.all %}
    <div class="panel-heading" style="background-image: url('{{ account.extra_data.profile_banner_url }}');"></div>
    <div class="panel-body text-center">
      
      <img class="panel-profile-img" src="{{ account.get_avatar_url }}">
    

      <h5 class="panel-title">
        {{user.first_name}} {{user.last_name}}
      </h5>

      <p class="m-b-md">{{account.extra_data.description}}</p>

      <ul class="panel-menu">
        <li class="panel-menu-item">
          
            Voted
            <h5 class="m-y-0">{{voted}}</h5>
          
        </li>

        <li class="panel-menu-item">
          
            Published
            <h5 class="m-y-0">{{posted}}</h5>
          
        </li>
      </ul>
    </div>
    {% endfor %}
  </div>

  <!--<div class="panel panel-default visible-md-block visible-lg-block">
    <div class="panel-body">
      <h5 class="m-t-0">Eventos· <small><a href="{% url 'blog:events'%}">Ver Todos</a></small></h5>
      <ul class="list-unstyled list-spaced">
        {% for event in events_list %}
        <li><span class="text-muted icon icon-arrow-right m-r"></span>{{event.title}}
        {% endfor %}
      </ul>
      <hr>
      <ul class="list-unstyled list-spaced">
        {% for event in events %}
        <li><span class="text-muted icon icon-arrow-right m-r"></span>{{event.title}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>-->
</div>
<div class="col-md-6">
  <ul class="nav nav-pills nav-justified">
    {% if view == 'votes' %}
    <li role="presentation" class="active"><a href="">Voted</a></li>
    <li role="presentation"><a href="{% url 'profile' 'posts' %}">Published</a></li>
    {% else %}
    <li role="presentation"><a href="{% url 'profile' 'votes'%}">Voted</a></li>
    <li role="presentation" class="active"><a href="">Published</a></li>
    {% endif %}
  </ul>

  <ul class="list-group media-list media-list-stream m-t-md">
    {% include page_template %}
  </ul>

</div>
{% include 'blog/right-col.html' %}
{% endblock %}

blog/templates/blog/faq.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block meta %}
    <meta name="description" content="Here you can find our Frequently Asked Questions (FAQ). We can't wait to see you share a great startup.">

    <meta property="og:title" content="FAQ | Earlist"/>
    <meta property="og:description" content="Here you can find our Frequently Asked Questions (FAQ). We can't wait to see you share a great startup."/>
    <meta name="twitter:description" content="Here you can find our Frequently Asked Questions (FAQ). We can't wait to see you share a great startup.">

    <meta property="og:image" content="http://earlist.xyz/media/images/20180815/earlist.png"/>
    <meta property="og:url" content="http://earlist.xyz/faq/"/>
    <meta name="twitter:card" content="summary">
    <meta name="twitter:url" content="http://earlist.xyz/faq/">
    <meta name="twitter:title" content="FAQ | Earlist">
    <meta name="twitter:image" content="http://earlist.xyz/media/images/20180815/earlist.png">

    <title>Terms of Service | Earlist</title>
{% endblock %}
{% block content %}
<div class="container p-t-md">
    <div class="row">
<div class="col-sm-offset-2 col-md-8">
  <div class="panel panel-default">
    <div class="panel-body m-t">
    <h1 class="text-center">Frequently Asked Questions</h1>
    <section class="contentSection">
    <br>
    <h4 class="contentSection__title">What is Earlist?</h4>
    <p class="contentSection__body">Earlist is the ultimate go-to place if you want to discover what’s next on blockchain,  technology, food and beverage, trends and much more. Here you can find all the awesome ideas you are looking for, and best of all, you can launch your own</p>
    <h4 class="contentSection__title">How do I submit my startup?</h4>
    <p class="contentSection__body">You can submit it here: <a href="{% url 'blog:post' %}">Share</a></p>
    <h4 class="contentSection__title">How do I advertise on Earlist?</h4>
    <p class="contentSection__body">You can't yet advertise on Earlist, but you can submit your startup an if it meets our criteria it will be featured for free.</a>.</p>
    <h4 class="contentSection__title">What happens after I submit my startup?</h4>
    <p class="contentSection__body">After you submit your startup, we will review it an see if it matches our criteria. If it is a good fit, you will receive an email when we post it to our site. It usually takes 1 month to get it featured. There's a paid option to expedite your post and publish instantly.
    <h4 class="contentSection__title">What is the selection criteria?</h4>
    <p class="contentSection__body">In general we like cool companies around blockchain, food and beverage, and overall tech.</a>.</p>
    <h4 class="contentSection__title">I don&rsquo;t match the selection criteria, will you make an exception?</h4>
    <p class="contentSection__body">No. These criteria are geared towards the preferences of our audience.</p>
</div>
</div>
</div>

{% endblock %}

blog/templates/blog/submit_job.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
<div class="col-sm-3"></div>
<div class="col-sm-6">
	<form action="{% url 'blog:job' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="title">Título del puesto</label>
			{{ form.title|attr:"placeholder:ej: AngularJS Software Engineer"|add_class:"form-control" }}
		</div>
		<div class="form-group">
			<label for="slogan">Compañía</label>
			{{ form.company|attr:"placeholder:ej: Beerhouse"|add_class:"form-control" }}
		</div>
		<div class="form-group">
			<label for="body">Página con descripción del puesto</label>
			{{ form.link|attr:"value:http://"|add_class:"form-control" }}
		</div>
		<div class="form-group">
			<label for="body">Logo de la compañía</label>
			{{ form.image_url|add_class:"form-control" }}
		</div>
		<div class="form-group">
			<input type='submit' value='Submit' class ="btn btn-primary w-full" />
		</div>
	</form>
</div>
{% endblock %}

blog/templates/blog/users.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load socialaccount %}
{% block content %}
<div class="col-md-1"></div>

<div class="col-md-10">
  <ul class="list-group media-list media-list-stream m-t">
  	{% for u in users_list %}
      <li class="media list-group-item p-a">
          {% for account in u.socialaccount_set.all %}
          <a class="media-left" href="#">
            <img class="media-object img-circle" src="{{ account.get_avatar_url }}">
          </a>
          {% endfor %}
          <div class="media-body">
            <div class="media-body-text">
              <div class="media-heading">
                <small class="pull-right text-muted">{{u.date_joined}}</small>
                <h5>{{u.username}}</h5>
              </div>
              <p>
                {{u.email}}
              </p>
              <ul class="media-list">
                {% for post in u.post_set.all %}
                <li class="media">
                  <a class="media-left" href="#">
                    <div title="{{item.title}}" style="
                            background: url('{{post.image_file.url}}');
                            background-size:cover;
                            background-position:center;
                            width:40px;
                            height:40px;
                            border-radius:5px;
                            ">
                    </div>
                  </a>
                  <div class="media-body">
                    <strong>{{post.title}}</strong>
                    <br>
                    {{post.slogan}}
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}